### ISSUE TITLE
Reorganize structure of projects under RhetosPackages\Source folder

### ISSUE THREAD

**Issue by ngoquoc** [Rhetos/AdminGui#24]
Motivation:
https://github.com/Rhetos/AdminGui/pull/20#discussion_r222561495

**Comment by thanhlm91** [comment]
> Motivation:
> [#20 (comment)](https://github.com/Rhetos/AdminGui/pull/20#discussion_r222561495)


How about moving projects from folder 'AdminGui\RhetosPackages\Source' to 'AdminGui\Plugins' ?

**Comment by thanhlm91** [comment]
> Motivation:
> [#20 (comment)](https://github.com/Rhetos/AdminGui/pull/20#discussion_r222561495)

**Comment by bantolov** [comment]
Looks good to me. Init & Run passes on my PC.
I'll merge it now, to avoid complications with merges that might arise from this kind of PR staying open for too long.

**Comment by ngoquoc** [comment]
This issue should be closed as PR #26 has been merged.
