### ISSUE TITLE
DotNetZip vulnerablity in AdminGui plugin

### ISSUE THREAD

**Issue by huynguyen-95** [Rhetos/AdminGui#40]
- There is security alert of GitHub about using DotNetZip.

Solution: Upgrade verstion to 1.11.0 or later

**Comment by huynguyen-95** [comment]
DotNetZip version 1.9.3 is dependency of Rhetos 2.0.0

**Comment by bantolov** [comment]
Yes, the cause of the problem is in Rhetos NuGet package, I should upgrade Rhetos it to newer version of DotNetZip.

Even if AdminGui package does not use DotNetZip directly, I think that the PR #41 is a good workaround for the warning.
