### ISSUE TITLE
Workflow and current build scripts are too complicated

### ISSUE THREAD

**Issue by nguyenlamlll** [Rhetos/AdminGui#8]
Current workflows and build scripts are too complicated for newcomers and even, for returning users. We should try to simplify these processes. Preferably, move the scripts to a `scripts` folder and update README.md with the new flows.

**Comment by huynguyen-95** [comment]
As my experience, after cloning project, we have to run **make** first. Then we will do following steps:
   - Run **Rhetos - CreateNugetPackages**
   - Run **Rhetos - PrepareAndDeploy**
   - Run **Rhetos - StartIISExpress**
But, the complicated @nguyenlamlll said is inside **Rhetos - PrepareAndDeploy**, it run **make** again.
And the target of **make** right now is
1. Prepare some folder which does not exist
2. Build all external plugins
3. install npm packages for AdminGui
4. Build AdminGUI (tsc + gulp)

**Comment by nguyenlamlll** [comment]
OK, a short update. After "a few hours" of discussion, we have come up with this design:

- We will implement a Powershell module that defines and implements all necessary functions used in build processes.
- The exposed commands (to the devs) are limited to `init`, `run`, and `publish`. Right now, they are just ps1 scripts which will make uses of the functions defined above. 
- `init` command will initialize and create all required prerequisites for a developer to begin working on this repository. 
- `run` command builds the plugins, AdminGui, create debug packages out of them, start an IISExpress server, and remove those debug packages. This is for debugging sessions on local dev machines. 
- `publish` command will build the plugins and AdminGui then create Release Nuget packages that are ready for production.

**Comment by ngoquoc** [comment]
The proposal looks perfect to me. It would be much convenient to work with AdminGUI then.

Can you please describe more details about the `init` command? I guess it would:
1. Install necessary development dependencies: IISExpress, .NET Framework, etc.?
2. Fetch Rhetos server binaries from GitHub?

**Comment by huynguyen-95** [comment]
About ```init``` command, at right now, it is used for:
- Download and extract Rhetos zip file from GitHub
- Initialize database
- Copy some configs file for Rhetos
- Create some neccessary directories

I guess, in ```init``, we need to:
1. Check IISExpress is exist?
2. Check MSBuild (which we will use to build plugins project by command line) is exist?
@ngoquoc if you think some steps need to do in```init```, just inform us.

**Comment by nguyenlamlll** [comment]
Checking before using them is a must but I don't think we need to install other build tools. Instead, put them as `Prerequisites` :D (So, SQL Server, IISExpress and MSBuild 13.0+?)
